<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="hplaptop" failures="1" tests="4" name="Login and Transactions Test" time="58.78" errors="0" timestamp="06 Mar 2024 09:39:13 GMT">
  <testcase classname="com.xyz.qa.testcases.LoginPageTest" name="loginTest" time="1.848"/>
  <testcase classname="com.xyz.qa.testcases.CustomerAccountPageTest" name="verifyCustomerAccountDetails" time="0.504"/>
  <testcase classname="com.xyz.qa.testcases.DepositPageTest" name="depositAmountAndVerifyTransaction" time="1.846"/>
  <testcase classname="com.xyz.qa.testcases.WithdrawPageTest" name="withdrawAmountAndVerifyTransaction" time="2.063">
    <failure type="java.lang.AssertionError" message="expected [Transaction Successful] but found [Transaction Failed. You can not withdraw amount more than the balance.]">
      <![CDATA[java.lang.AssertionError: expected [Transaction Successful] but found [Transaction Failed. You can not withdraw amount more than the balance.]
	at com.xyz.qa.testcases.WithdrawPageTest.withdrawAmountAndVerifyTransaction(WithdrawPageTest.java:41)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- withdrawAmountAndVerifyTransaction -->
  <testcase classname="com.xyz.qa.testcases.LoginPageTest" name="customerLoginTest" time="0.0">
    <ignored/>
  </testcase> <!-- customerLoginTest -->
  <testcase classname="com.xyz.qa.testcases.LoginPageTest" name="loginPageTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginPageTitleTest -->
</testsuite> <!-- Login and Transactions Test -->
